### ISSUE TITLE
Clicking the "attack bonus" field on a warrior sheet with a die in the field rolls a die

### ISSUE THREAD

**Issue by algnc** [foundryvtt-dcc/foundryvtt-dcc#127]
On a Warrior, if I click into the field to edit it, it rolls a die.
![image](https://user-images.githubusercontent.com/7275595/107795817-26f9f680-6d27-11eb-8c45-4afb256cdd14.png)

**Comment by cyface** [comment]
@mooped do we want to fix this one before you merge in your big branch?
