### ISSUE TITLE
Fix up or delete the 'Shortened Macro Syntax' setting.

### ISSUE THREAD

**Issue by mooped** [foundryvtt-dcc/foundryvtt-dcc#139]
Looks like this came from the donor system, but is now non-functional.

We need to decide if it's worth keeping and if so make it work, otherwise just delete it.

Personally I think it's a worthwhile feature for ad-hoc rolls, though if it doesn't work in our Sheet fields there's a trade off between the complexity of fixing that vs inconsistency and potential confusion.

**Comment by cyface** [comment]
@algnc can you test this one?

**Comment by algnc** [comment]
Option is gone. Looks good.
