### ISSUE TITLE
HTML Issue on Halfling Sheet

### ISSUE THREAD

**Issue by cyface** [foundryvtt-dcc/foundryvtt-dcc#149]
Shouldn't see the `& gt ;` on this sheet:

![image](https://user-images.githubusercontent.com/49695/109400955-f7431500-7908-11eb-8e24-95990953fc8f.png)

**Comment by mooped** [comment]
Not sure if this is a recent change or something that's always been there. We can either use triple handlebars {{{ }}} on the sheet template to carry over HTML formatting or possibly just use an & instead of an &gt; escape in the localisation json.

**Comment by cyface** [comment]
I'd just update the localization JSON!
