### ISSUE TITLE
System Rolls with Custom Output Format Should Support Roll Options Like Private

### ISSUE THREAD

**Issue by mooped** [foundryvtt-dcc/foundryvtt-dcc#150]
If you roll a monster attack, and set it to be a private roll, the system should keep that roll private.

**Comment by cyface** [comment]
I think we're good on this one, but I wasn't able to test super well. @algnc can you validate this one?

**Comment by algnc** [comment]
Set rolls to Private (GM) and rolled attacks with a player logged in another browser - looked good.
