### ISSUE TITLE
Opt-in to bug reporter module

### ISSUE THREAD

**Issue by cyface** [foundryvtt-dcc/foundryvtt-dcc#152]
https://github.com/League-of-Foundry-Developers/bug-reporter

In system.json:
```
"bugs": "https://github.com/foundryvtt-dcc/foundryvtt-dcc/issues",
"allowBugReporter": true
```

**Comment by mooped** [comment]
Looks good, and seemed to submit a test bug just fine.

I've also added a dependency, but need to see how that works when installing a package. When updating an installed module (i.e. dev setup) Foundry was a bit confused until I manually installed the module and it wasn't enabled by default in my worlds.
