### ISSUE TITLE
NPC and PC stat block parser missing in latest update

### ISSUE THREAD

**Issue by ProgLord** [foundryvtt-dcc/foundryvtt-dcc#154]
The stat block parser is missing. It used to be at the top of the sheets, but it appears to be gone. Did it move or is this a bug?

**Comment by mooped** [comment]
@ProgLord It's moved to Import Actor(s) button at the bottom of the actors tab.

You can now paste multiple PSG text characters or statlines into the dialog and the actors will be created from the pasted data. Optionally you can have them import straight to a folder.
