### ISSUE TITLE
NPC Import Doesn't Handle NPCs with Equipment

### ISSUE THREAD

**Issue by cyface** [foundryvtt-dcc/foundryvtt-dcc#16]
For example:

`Green-robed smultist (1): Init +4; Atk dagger +5 melee (1d4+3); AC 11; HD 5d4+5; hp 21; MV 20’; SP 3d6 control check, able to cast arms of the angel, squid-mass (when killed, an squid-mass emerges; see stats below); Act 1d20; SV Fort +3, Ref +4, Will +0; AL C. Equipment: bird-shaped talisman of gold tied on a leather thong (worth 10 gp; see level 3).`

**Comment by mooped** [comment]
I'm not sure how standard the equipment is. However the full statline now gets inserted into the notes automatically on import, so the equipment (and any stats that failed to parse) are at least available.

I'm also tweaking the regex that matches the name to be a non-greedy match so it never goes past the first colon (currently this statline put everything up to the colon after Equipment into the name field).

![image](https://user-images.githubusercontent.com/371357/106669865-37ca9f80-65a4-11eb-94d7-6a06166cb403.png)
