### ISSUE TITLE
Improve the Formatting of the Halfling Tab

### ISSUE THREAD

**Issue by cyface** [foundryvtt-dcc/foundryvtt-dcc#170]
The "Sneak and Hide" text should be closer to, and vertically aligned with, it's value box.  The value box should also be shorter.

The whole thing should be left-aligned, rather than centered-ish. 👍🏻 

<img width="583" alt="image" src="https://user-images.githubusercontent.com/49695/110245983-ee62cc80-7f22-11eb-94e3-c77f056a22c7.png">

**Comment by mooped** [comment]
![image](https://user-images.githubusercontent.com/371357/111910044-a16d1300-8a57-11eb-85cc-639d0115ff1d.png)

Current version on dev-v0.24.0

**Comment by cyface** [comment]
Let's remove the "Halfling Skills" header.  

Need to link the Infravision item to that journal entry.

Need to add the link to the Halfing journal entry if they have the core book installed.

**Comment by mooped** [comment]
Skills header is gone. I'm creating a new task for the various links so I can stay organised.

**Comment by mooped** [comment]
See https://github.com/foundryvtt-dcc/foundryvtt-dcc/issues/196
