### ISSUE TITLE
Improve Formatting for "Wizard" Tab

### ISSUE THREAD

**Issue by cyface** [foundryvtt-dcc/foundryvtt-dcc#173]
The Wizard tab needs a dusting of formatting love.

Move the Spell Check Text and box closer to each other, make the spell check box shorter, align them vertically, and far left like the other fields on this tab.

Add padding to match other fields between the labels and the fields.

Align the field labels on top of the fields like on other top-labeled fields.

Add padding between the fields and the surround box.

<img width="605" alt="image" src="https://user-images.githubusercontent.com/49695/110246326-67aeef00-7f24-11eb-84bf-f9ae204a844a.png">

**Comment by mooped** [comment]
![image](https://user-images.githubusercontent.com/371357/111910169-2f48fe00-8a58-11eb-88fb-2bd4956af248.png)

Current version on dev-v0.24.0

**Comment by cyface** [comment]
Do we perhaps want to label Corruption as Corruptions and make it a big text field?

**Comment by cyface** [comment]
Let's remove the "Wizard Abilities" header.

**Comment by mooped** [comment]
Header removed.

Corruption issue is represented by https://github.com/foundryvtt-dcc/foundryvtt-dcc/issues/197

**Comment by cyface** [comment]
Looks good in preview-0.24
