### ISSUE TITLE
Improve Formatting on the "Cleric" Tab

### ISSUE THREAD

**Issue by cyface** [foundryvtt-dcc/foundryvtt-dcc#174]
The Cleric tab needs a dusting of formatting love.

Vertically align field labels with fields.

Labels in the two-column fields at the top should be ragged-left - and their right sides should be tight to the fields they are labelling.

That includes when you switch to one col for Deity and Disapproval Table.

<img width="614" alt="image" src="https://user-images.githubusercontent.com/49695/110246464-ead04500-7f24-11eb-8d8c-a92336dc023e.png">

**Comment by mooped** [comment]
![image](https://user-images.githubusercontent.com/371357/111910067-c06ba500-8a57-11eb-84c8-0a75a19bccf6.png)

Current version on dev-v0.24.0

**Comment by cyface** [comment]
Seems to be that the disapproval drop down is just a bit too wide?

**Comment by cyface** [comment]
Maybe just kill the right and left borders on the disapproval table?

**Comment by cyface** [comment]
Can we bold the column headers on the disapproval table.

**Comment by cyface** [comment]
Let's remove the "Cleric Abilities" header.

**Comment by mooped** [comment]
I've tweaked the disapproval dropdown and removed the "Cleric Abilities" header.

I've created a new task https://github.com/foundryvtt-dcc/foundryvtt-dcc/issues/199 to rework the Lay On Hands table section.

**Comment by cyface** [comment]
Very close in preview-.24, just need a line under the column labels on the healing chart:
![image](https://user-images.githubusercontent.com/49695/113322785-5c0bd980-92d2-11eb-942e-db5e5ccdc889.png)

**Comment by mooped** [comment]
![image](https://user-images.githubusercontent.com/371357/113448912-a71e0d80-93f4-11eb-91fd-3f955d9c1389.png)

I've reworked it as a grid layout to allow the borders to work correctly, and reworked the layout to give some whitespace left, right, and in between the table.

**Comment by cyface** [comment]
That looks much better! Is there a head that describes what that table is?
