### ISSUE TITLE
Improve Formatting on the "Thief" Tab

### ISSUE THREAD

**Issue by cyface** [foundryvtt-dcc/foundryvtt-dcc#175]
The "Thief" tab on the character sheet could use a dusting of formatting love.

Vertically align all labels with fields.

Field labels should be "ragged left", and their right sides should be close to the field they are labelling.

Slightly shorten the bonus field for cast spell from scroll to give some padding between the die and bonus fields.

<img width="611" alt="image" src="https://user-images.githubusercontent.com/49695/110246644-9f6a6680-7f25-11eb-8c49-0bed3504e98f.png">

**Comment by mooped** [comment]
![image](https://user-images.githubusercontent.com/371357/111910181-3cfe8380-8a58-11eb-9dc8-711a2206bb6b.png)

Current version on dev-v0.24.0

**Comment by cyface** [comment]
This looks good, just need to remove the "Thief Skills" header.

**Comment by cyface** [comment]
Looks good in preview-.24
