### ISSUE TITLE
Improve Formatting for the "Warrior" Tab

### ISSUE THREAD

**Issue by cyface** [foundryvtt-dcc/foundryvtt-dcc#176]
The "Warrior" tab on the character sheet needs a sprinkling of formatting love.

Vertically-align all labels with their fields.

Move labels and fields to be left-justified, but ragged-left, with their right sides close to the field their are labelling.

<img width="606" alt="image" src="https://user-images.githubusercontent.com/49695/110246743-0be56580-7f26-11eb-902f-ead26e6d3958.png">

**Comment by mooped** [comment]
![image](https://user-images.githubusercontent.com/371357/111910128-04f74080-8a58-11eb-980b-2544b7b73062.png)

Current version on dev-v0.24.0

**Comment by cyface** [comment]
Is it possible to make the threat range a drop-down?

**Comment by cyface** [comment]
Can we add the link to the warrior journal at the bottom of this tab, perhaps?

**Comment by cyface** [comment]
The text inside the value boxes should be left-aligned if the label is on the left.  The 20 is ok, but lucky weapon should be left-aligned inside the value box.

**Comment by cyface** [comment]
Let's remove the "Warrior Abilities" header.

**Comment by mooped** [comment]
Text is aligned and the header is removed.

Will add a dropdown under this issues.

Link related issues are aggregated here in https://github.com/foundryvtt-dcc/foundryvtt-dcc/issues/196

**Comment by mooped** [comment]
Linking is aggregated under https://github.com/foundryvtt-dcc/foundryvtt-dcc/issues/196

The crit range issue now lives here https://github.com/foundryvtt-dcc/foundryvtt-dcc/issues/198

Everything else from this issue is resolved.

**Comment by cyface** [comment]
Looks good in preview-0.24
