### ISSUE TITLE
Improve Formatting on the "Dwarf" Tab

### ISSUE THREAD

**Issue by cyface** [foundryvtt-dcc/foundryvtt-dcc#177]
The "Dwarf" tab on the character sheet could use a sprinkle of formatting love.

Vertically align all labels to the field they are labelling.

Left-justify the fields, with their labels ragged-left, so that their right sides are close to the field that they are labelling.

Add " 60' " to the Infravision help text.

<img width="611" alt="image" src="https://user-images.githubusercontent.com/49695/110246795-4c44e380-7f26-11eb-80c8-2a7125089bff.png">

**Comment by mooped** [comment]
![image](https://user-images.githubusercontent.com/371357/111910141-13455c80-8a58-11eb-83ff-7a83d411da09.png)

Current version on dev-v0.24.0

**Comment by cyface** [comment]
The text inside the fields shouldn't be centered if their labels aren't above the fields. 👍🏻 Also need to link Infravision and Mighty deeds to their journal entries.

**Comment by cyface** [comment]
Let's remove the "Dwarf Abilities" header.

**Comment by mooped** [comment]
Link related issues aggregated in https://github.com/foundryvtt-dcc/foundryvtt-dcc/issues/196

Everything else is done.

**Comment by cyface** [comment]
Looks good in preview-0.24....other than linking Infravision to that journal entry

**Comment by mooped** [comment]
Cool. Links will be added with #196.
