### ISSUE TITLE
Cheat Sheet for Infravision

### ISSUE THREAD

**Issue by cyface** [foundryvtt-dcc/foundryvtt-dcc#179]
Create a JounalEntry cheat sheet for Infravision.

"here'e everything we know about Infravision, including how to wire it up on a token, and summarizing everything we can find about it, rule-wise".

Try and cut through the 5e FUD around how the tokens and lighting work, as well as any DCC rules clarifications that have become tribal knowledge.

Link to this JournalEntry from the Class JournalEntries that have Infravision.

Link to this JournalEntry from the Class Tabs on character sheets that have Infravision.

**Comment by algnc** [comment]
Cheat sheet created

**Comment by algnc** [comment]
Completed in dev.
