### ISSUE TITLE
Cheat Sheet for Mighty Deeds

### ISSUE THREAD

**Issue by cyface** [foundryvtt-dcc/foundryvtt-dcc#180]
Create a JounalEntry cheat sheet for Mighty Deeds.

"Here'e everything we know about Might Deeds, including how to wire it up on your sheet, and summarizing everything we can find about it, rule-wise".

Try and make it clear how it works in game and in Foundry, as well as any DCC rules clarifications that have become tribal knowledge.

Link to this JournalEntry from the Class JournalEntries that have Mighty Deeds.

Link to this JournalEntry from the Class Tabs on character sheets that have Mighty Deeds.

**Comment by algnc** [comment]
Cheat sheet linked.
