### ISSUE TITLE
Improve Formatting on the "Elf" Tab

### ISSUE THREAD

**Issue by cyface** [foundryvtt-dcc/foundryvtt-dcc#182]
The "Elf" tab on the character sheet could use some pixie-dust.

Move the Spell Check Text and box closer to each other, make the spell check box shorter, align them vertically, and far left like the other fields on this tab.

Align the field labels on top of the fields like on other top-labeled fields.

<img width="609" alt="image" src="https://user-images.githubusercontent.com/49695/110248100-af397900-7f2c-11eb-88bd-f04c4b5336e6.png">

**Comment by mooped** [comment]
Spell out the +4 bonus to Find Secret Doors.

**Comment by mooped** [comment]
![image](https://user-images.githubusercontent.com/371357/111910152-1fc9b500-8a58-11eb-83a3-4663c0acf98f.png)

Current version on dev-v0.24.0

**Comment by cyface** [comment]
Let's remove the "Elf Abilities" header.

**Comment by cyface** [comment]
Is "Find Secret Doors" rollable? If not, seems like it could/should be?

Can we make "Corruption" "Corruptions", and make it a big text field?

**Comment by mooped** [comment]
Secret doors has always been rollable and the header is gone.

Link related issues aggregated in https://github.com/foundryvtt-dcc/foundryvtt-dcc/issues/196

Corruption field issues aggregated in https://github.com/foundryvtt-dcc/foundryvtt-dcc/issues/197

**Comment by cyface** [comment]
Looks good in preview-.024
