### ISSUE TITLE
 Spell items pick up world spell tables to roll on even though compendium entries exist #77 

### ISSUE THREAD

**Issue by algnc** [foundryvtt-dcc/foundryvtt-dcc#183]
For spells which may have a RollTable matching them in the world, spells rolled from the sheet seem to pick up world RollTables that match and roll off them. This could impact a user unknowingly.

This is easily reproducable by creating a table called Spider Climb, then rolling Spider Climb.

![image](https://user-images.githubusercontent.com/7275595/110634630-2d3d9000-8178-11eb-8c56-318c230e5e3d.png)

**Comment by cyface** [comment]
@algnc I'll have you be the tester on this one if you don't mind. :)

**Comment by algnc** [comment]
Tested on my world with a junk spell. Works fine now
