### ISSUE TITLE
Changing an owned spell to level 0 clears all data on sheet

### ISSUE THREAD

**Issue by algnc** [foundryvtt-dcc/foundryvtt-dcc#189]
If you assign a spell to someone (in this case with a custom spell tab) and change the level of the spell to 0, it will hide all spells, equipment, etc. on the sheet with the error:

Uncaught (in promise) TypeError: spells[i.data.level] is undefined
    _prepareItems https://bloatware.asuscomm.com:1444/systems/dcc/module/actor-sheet.js:153
    getData https://bloatware.asuscomm.com:1444/systems/dcc/module/actor-sheet.js:88
    getData https://bloatware.asuscomm.com:1444/systems/dcc/module/actor-sheets-dcc.js:86
    _render https://bloatware.asuscomm.com:1444/scripts/foundry.js:4509
    _render https://bloatware.asuscomm.com:1444/scripts/foundry.js:5157
    _render https://bloatware.asuscomm.com:1444/scripts/foundry.js:16788
    render https://bloatware.asuscomm.com:1444/scripts/foundry.js:4479
    render https://bloatware.asuscomm.com:1444/scripts/foundry.js:5621
    render https://bloatware.asuscomm.com:1444/scripts/foundry.js:29079
    _onModifyEmbeddedEntity https://bloatware.asuscomm.com:1444/scripts/foundry.js:30200
    _onModifyEmbeddedEntity https://bloatware.asuscomm.com:1444/scripts/foundry.js:31173
    _handleUpdateEmbeddedEntity https://bloatware.asuscomm.com:1444/scripts/foundry.js:30051
    updateEmbeddedEntity https://bloatware.asuscomm.com:1444/scripts/foundry.js:30015
actor-sheet.js:153:11

Easily reproducible by giving a level 1 warrior equipment, a custom spell tab, then change a spell to level 0.
​

**Comment by algnc** [comment]
Same issue with a level 1 Wizard

**Comment by mooped** [comment]
Worth noting that the items are still present, just failing to render.

I've made a HotFix which Tim should be able to release soon. Once applied everything will come back.
