### ISSUE TITLE
Improve Styling of Journal Entries

### ISSUE THREAD

**Issue by cyface** [foundryvtt-dcc/foundryvtt-dcc#193]
Update the font of the name field to be Duvall, and the body text to be Book Antiqua.

**Comment by mooped** [comment]
Are we happy for this to be all journal entries while our system is active?

**Comment by cyface** [comment]
I think it’s worth a try? Maybe try it with just the titles and see how it looks?

**Comment by cyface** [comment]
Not seeing body text as book Antiqua, but the headings now look good in preview-.24!

**Comment by mooped** [comment]
I missed the body test suggestion :/ Will update it soon.
