### ISSUE TITLE
Add appropriate links to class sheets

### ISSUE THREAD

**Issue by mooped** [foundryvtt-dcc/foundryvtt-dcc#196]
From existing issues:

- Dwarf
  - Infravision
  - Mighty Deeds
- Elf
  - Infravision
- Halfling
  - Infravision
Warrior
  - Mighty Deeds

Also links to class entries if available (core book installed)

**Comment by algnc** [comment]
@mooped if the code is added to allow links, I can handle adding the links

**Comment by mooped** [comment]
Ok, code support exists now on the dev branch.

For example:

`
                    {{#dccPackExists "dcc-core-book.dcc-core-equipment"}}
                      <li>{{dccLocalizeAndEnrich "DCC.InfravisionLink"}}</li>
                    {{else}}
                      <li>{{localize "DCC.Infravision"}}</li>
                    {{/dccPackExists}}
`

Replace the pack name in dccPackExists with the appropriate pack, then make the DCC.InfravisionLink locstring contain the appropriate link.

**Comment by algnc** [comment]
Added warrior links

**Comment by algnc** [comment]
![Uploading image.png…]()

**Comment by algnc** [comment]
![image](https://user-images.githubusercontent.com/7275595/113515175-d9d51c80-9540-11eb-89ea-2bf672f9b42c.png)

**Comment by algnc** [comment]
Completed in dev.
