### ISSUE TITLE
Make Warrior's crit range a drop down

### ISSUE THREAD

**Issue by mooped** [foundryvtt-dcc/foundryvtt-dcc#198]

**Comment by cyface** [comment]
Not seeing this in preview-.24

**Comment by mooped** [comment]
![image](https://user-images.githubusercontent.com/371357/113443970-e0518000-93ea-11eb-9e10-53955479b709.png)

@cyface Have I misunderstood what you were suggesting with this issue? It's there for me as in the screenshot.

**Comment by cyface** [comment]
Yep, I was suggesting we make the drop-down the whole range, e.g. 20-20, 19-20, etc.  you can keep the “value” of the drop down as just the bottom number, so the code doesn’t need to change....

**Comment by mooped** [comment]
That makes sense. :)

![image](https://user-images.githubusercontent.com/371357/113446509-ccf4e380-93ef-11eb-994d-22827555b598.png)

Alignment of text in a dropdown is awkward, but hopefully we can live with it.

**Comment by algnc** [comment]
Looks good
