### ISSUE TITLE
Mercurial Effects for spells that change the casting dice

### ISSUE THREAD

**Issue by mindshadow2k** [foundryvtt-dcc/foundryvtt-dcc#205]
There is a spell mercurial effect that modifies the casting dice and it appears there is no way to change this for individual spells.

**Comment by algnc** [comment]
hit the pencil (edit icon) on the right of the spell, hit Config on the window that opens for the spell (top bar) then uncheck Inherit Action die. Now you can edit the Spell Check field to any die you want.

**Comment by mindshadow2k** [comment]
Of course didn’t even think to hit that!  Thanks for the quick response!
