### ISSUE TITLE
Reduce Font Size of Text in "Birth Augur" field

### ISSUE THREAD

**Issue by cyface** [foundryvtt-dcc/foundryvtt-dcc#210]
As tested in preview-0.24, the text in the Birth Augur field is too large:

![image](https://user-images.githubusercontent.com/49695/113322495-ff102380-92d1-11eb-900b-bac41b783976.png)

either need to shink the text, or make the box taller.

**Comment by mooped** [comment]
I've tweaked both this and Languages, which has the same issue.

![image](https://user-images.githubusercontent.com/371357/113446129-1690fe80-93ef-11eb-8018-d45d01112202.png)

**Comment by algnc** [comment]
Looks good
