### ISSUE TITLE
When rolling an attack for a weapon that has invalid values in the "To Hit" and "Damage" fields, nothing appears in the chat

### ISSUE THREAD

**Issue by ckwk** [foundryvtt-dcc/foundryvtt-dcc#25]
Where the user would normally expect the chat to be populated with a roll, possibly with "N/A"s or similar error messages in applicable rolls, instead nothing appears in the chat.

![image](https://user-images.githubusercontent.com/44243499/90055562-c36d0e80-dc9a-11ea-9b45-21b92698b51c.png)

**Comment by mooped** [comment]
I'm not completely happy with this, but it works and there's now a framework for improving it further.

For inline rolls:
![image](https://user-images.githubusercontent.com/371357/106814222-f8668680-6669-11eb-879d-a545e304f071.png)

And for standard chat card rolls:
![image](https://user-images.githubusercontent.com/371357/106814313-1cc26300-666a-11eb-8654-fca4999790f1.png)

**Comment by mooped** [comment]
Would be nice to have a way of making intentionally invalid formulae just display on the card, for things that automatically hit or do special damage, without making errors unclear. Maybe just showing the formula would be enough for those cases.
