### ISSUE TITLE
Handle natural 1s and 20s on spell check rolls

### ISSUE THREAD

**Issue by algnc** [foundryvtt-dcc/foundryvtt-dcc#53]
Checking for natural 1s on spell rolls would indicate when corruption or a misfire occured. it could also check for natural 20s to add double caster level.

edit: actually, I see now you get a red number on a 1. That should work. Natural 20 could double caster level which would be nice.

**Comment by mooped** [comment]
Updated title to reflect the edit.

**Comment by mooped** [comment]
Likewise we should handle natural 1s which seem to be another special case.

**Comment by cyface** [comment]
@algnc can you validate this one in preview-0.24?

**Comment by algnc** [comment]
both fumble and crit roll and total their rolls correctly now!
